# Generated by Django 6.0.5 on 2026-05-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.TextField(help_text='Bitmap encoded as base64.')),
                ('annotation', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discount', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
