# Generated by Django 6.0.5 on 2026-05-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='purchased_product_ids',
        ),
        migrations.AddField(
            model_name='customer',
            name='purchased_cards',
            field=models.ManyToManyField(blank=True, related_name='customers', to='cards.card', verbose_name='Купленные карточки'),
        ),
    ]
